apiVersion: apps/v1
kind: Deployment
metadata:
  name: deply-tgramscrape
  labels:
    app: scraper
    type: httpweb
    platform: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      name: pod-tgramscrape
      labels:
        app: scraper
        type: httpweb
        platform: telegram
    spec:
      containers:
        - name: ctn-tgramscrape
          image: kneerunjun/tgramscraper:1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_user
            - name: AMQP_PASSWD
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_passwd
            - name: AMQP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_server
          