apiVersion: apps/v1
kind: Deployment
metadata:
  name: deply-tgramscrape
  labels:
    app: scraper
    type: httpweb
    platform: telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      name: pod-tgramscrape
      labels:
        app: scraper
        type: httpweb
        platform: telegram
    spec:
      containers:
        - name: ctn-tgramscrape
          image: kneerunjun/tgramscraper:1.5.2
          imagePullPolicy: Always
          volumeMounts:
            - name: vol-tgramsecrets
              mountPath: /run/secrets/vol-tgramsecrets
              readOnly: true
          ports:
            - containerPort: 8080
          env:
            - name: AMQP_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_user
            - name: AMQP_PASSWD
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_passwd
            - name: AMQP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: amqp_server
            - name: BASEURL
              valueFrom:
                configMapKeyRef:
                  name: telegram-config
                  key: base_url
            - name: NIRCHATID
              valueFrom:
                configMapKeyRef:
                  name: telegram-config
                  key: nir_chatid
      volumes:
        - name: vol-tgramsecrets
          secret: 
            secretName: tgram-secret
          