apiVersion: v1
kind: Service
metadata:
 name: svc-rabbit
spec:
 type: NodePort
 ports:
  - port: 81
    targetPort: 15672
    nodePort: 30072
    protocol: TCP
    name: mgmtguiport
  - port: 5672
    targetPort: 5672
    nodePort: 30073
    protocol: TCP
    name: apiport
 selector:
  app: rabbitmq