apiVersion: apps/v1
kind: Deployment
metadata:
  name: deply-rabbit
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: pod-rabbit
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        storage: hdd100G
      containers:
        - name: ctn-rabbit
          image: rabbitmq:3.13-rc-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 15672 # port over which the management console can be accessed
            - containerPort: 5672 # port over which api can be accessed 